server:
  address: "::"
  port: 2333
  http2:
    enabled: true

lavalink:
  plugins:
    - dependency: dev.lavalink.youtube:youtube-plugin:755aab35029153a705ebd4be63c56a55d68ae678
      snapshot: true
    - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.8.1
      snapshot: false
  pluginsDir: ./plugins
  server:
    password: "mipasswordsegura"
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: MEDIUM
    trackStuckThresholdMs: 90000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      http: true
      local: false

plugins:
  lavasrc:
    providers:
      - "ytsearch:%ISRC%"
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: true
      deezer: true
      yandexmusic: false
      flowerytts: false
      youtube: false
    spotify:
      clientId: "c187d712e9c7481d9cfe54a6afff0951"
      clientSecret: "d58a2b07766e4f2cbdfde2b11ddbb777"
      countryCode: "CO"
      playlistLoadLimit: 6
      albumLoadLimit: 6
    applemusic:
      countryCode: "CO"
      playlistLoadLimit: 6
      albumLoadLimit: 6
    deezer:
      masterDecryptionKey: "..."
      arl: "55e2c40111dcaeb3b13a539ded14ecde38a666b87ac066e3103fcc75de5ac181d9415508fb3ea19314b069cd497f519d3037595e3c3c230a1a14d46ec8167cb402d03c345cc3aa57f469f305aa42b53f6d5a1605ec5ecb527849e5660b6d91b7"
  youtube:
    enabled: true
    oauth:
      refreshToken: ${GOOGLE_REFRESH_TOKEN}      
    clients:
      - TV
      - TVHTML5EMBEDDED
      - MWEB
      - WEB
      - WEBEMBEDDED
      - MUSIC
      - ANDROID_VR
      - IOS
    clientOptions:
      TVHTML5EMBEDDED:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      WEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: true
      MUSIC:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
    